// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function init(value) {
  return /* record */[
          /* value */value,
          /* next */undefined
        ];
}

function append(node, value) {
  var match = node[/* next */1];
  if (match !== undefined) {
    return /* record */[
            /* value */node[/* value */0],
            /* next */append(match, value)
          ];
  } else {
    var newNode = /* record */[
      /* value */value,
      /* next */undefined
    ];
    return /* record */[
            /* value */node[/* value */0],
            /* next */newNode
          ];
  }
}

var x = /* record */[
  /* value */4,
  /* next */undefined
];

var y = append(x, 6);

var z = append(y, 9);

var w = append(z, 24);

console.log(w[/* next */1]);

exports.init = init;
exports.append = append;
exports.x = x;
exports.y = y;
exports.z = z;
exports.w = w;
/* y Not a pure module */
